ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Models/Citta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASPCORE_Lez4_Impiegati.Models
{
    [Table("Citta")]
    public class Citta
    {
        [Column("CittaID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string NomeCitta { get; set; }
    }
}

ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Models/Impiegato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ASPCORE_Lez4_Impiegati.Models
{
    [Table("Impiegati")]
    public class Impiegato
    {
        [Column("ImpiegatoID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Codice { get; set; }

        [Required(ErrorMessage = "Il campo Nome è obbligatorio")]
        [MinLength(3, ErrorMessage = "Il campo Nome è troppo corto")]
        [StringLength(255, ErrorMessage = "Il campo Nome è troppo lungo")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Il campo Cognome è obbligatorio")]
        [MinLength(3, ErrorMessage = "Il campo Cognome è troppo corto")]
        [StringLength(255, ErrorMessage = "Il campo Cognome è troppo lungo")]
        public string Cognome { get; set; }

        [Required(ErrorMessage = "Il campo Titolo è obbligatorio")]
        [StringLength(255, ErrorMessage = "Il campo Titolo è troppo lungo")]
        public string Titolo { get; set; }

        [Required(ErrorMessage = "Il campo Città di residenza è obbligatorio")]
        [StringLength(255, ErrorMessage = "Il campo Città di residenza è troppo lungo")]
        public string Citta { get; set; }

        public Impiegato()
        {
            Codice = Guid.NewGuid().ToString();
        }

    }
}

ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Controllers/ImpiegatoController.cs
using ASPCORE_Lez4_Impiegati.Data;
using ASPCORE_Lez4_Impiegati.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPCORE_Lez4_Impiegati.Controllers
{
    public class ImpiegatoController : Controller
    {
        private readonly InterfaceRepo<Impiegato> _repositoryImp;
        private readonly InterfaceRepo<Citta> _repositoryCit;

        public ImpiegatoController(InterfaceRepo<Impiegato> repImp, InterfaceRepo<Citta> repCit)
        {
            _repositoryImp = repImp;
            _repositoryCit = repCit;
        }


        public IActionResult Lista()
        {
            List<Impiegato> elenco = (List<Impiegato>)_repositoryImp.GetAll();

            ViewBag.Title = "Lista impiegati";

            return View(elenco);
        }

        private List<SelectListItem> PopolaCitta()
        {
            List<Citta> cittadine = (List<Citta>)_repositoryCit.GetAll();

            List<SelectListItem> selectBox = new List<SelectListItem>();

            // <option value="Value">Text</option>

            foreach (var item in cittadine)
            {
                selectBox.Add(
                    new SelectListItem()
                    {
                        Text = item.NomeCitta,
                        Value = item.NomeCitta
                    });
            }

            return selectBox;
        }

        public IActionResult Inserisci()
        {
            ViewBag.Citta = PopolaCitta();

            return View();
        }

        [HttpPost]
        public IActionResult Inserisci(Impiegato objImp)
        {
            ViewBag.Citta = PopolaCitta();

            if (ModelState.IsValid)
            {
                _repositoryImp.Insert(objImp);
                return Redirect("/");
            }
            else
            {

                return View(objImp);
            }

        }

        public IActionResult Dettaglio(string varCodice)
        {

            ViewBag.Citta = PopolaCitta();

            Impiegato temp = _repositoryImp.GetFromCodice(varCodice);

            if (temp == null)
                return Redirect("Impiegato/Errore");

            return View(temp);
        }

        [HttpPost]
        public IActionResult Modifica(Impiegato objImp)
        {

            //TODO...
            return View();
        }

        [HttpDelete]
        public ActionResult Elimina(string varCodice)
        {
            //TODO...
            return Ok(new { Status = "success" });
        }
    }
}

ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Views/Impiegato/Dettaglio.cshtml
@model ASPCORE_Lez4_Impiegati.Models.Impiegato
@{
    Layout = "_Layout";
}

<div class="row">
    <div class="col">

        <form asp-controller="Impiegato" asp-action="Modifica" method="post">
            <div class="form-group">
                <label asp-for="Nome">Nome:</label>
                <input type="text" asp-for="Nome" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Nome"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cognome">Cognome:</label>
                <input type="text" asp-for="Cognome" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Cognome"></span>
            </div>

            <div class="form-group">
                <label asp-for="Titolo">Titolo:</label>
                <input type="text" asp-for="Titolo" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Titolo"></span>
            </div>

            <div class="form-group">
                <label>Città:</label>
                <select class="form-control" asp-for="Citta" asp-items="@ViewBag.Citta">
                    <option value="">Seleziona la Cittò</option>
                </select>

                <span asp-validation-for="Citta"></span>
            </div>

            <button type="submit" class="btn btn-block">Modifica</button>
        </form>

    </div>
</div>

ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Views/Impiegato/Inserisci.cshtml
@model ASPCORE_Lez4_Impiegati.Models.Impiegato
@{ 
    Layout = "_Layout";
}

<div class="row">
    <div class="col">

        <form asp-controller="Impiegato" asp-action="Inserisci" method="post">

            <div class="form-group">
                <label asp-for="Nome">Nome:</label>
                <input type="text" asp-for="Nome" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Nome"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cognome">Cognome:</label>
                <input type="text" asp-for="Cognome" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Cognome"></span>
            </div>

            <div class="form-group">
                <label asp-for="Titolo">Titolo:</label>
                <input type="text" asp-for="Titolo" placeholder="Inserisci il valore" class="form-control" />
                <span asp-validation-for="Titolo"></span>
            </div>

            <div class="form-group">
                <label>Città:</label>
                <select class="form-control" asp-for="Citta" asp-items="@ViewBag.Citta">
                    <option value="">Seleziona la Cittò</option>
                </select>

                <span asp-validation-for="Citta"></span>
            </div>

            <button type="submit">Inserisci</button>
        </form>

    </div>
</div>

ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Views/Impiegato/Lista.cshtml
@model List<ASPCORE_Lez4_Impiegati.Models.Impiegato>

@{ 
    Layout = "_Layout";
}

<h1>Lista impiegati</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Codice</th>
            <th>Città</th>
            <th>Titolo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nome</td>
                <td>@item.Cognome</td>
                <td>
                    <a href="/Impiegato/Dettaglio/@item.Codice">@item.Codice</a>
                </td>
                <td>@item.Citta</td>
                <td>@item.Titolo</td>
                <td>
                    <button type="button" class="btn btn-danger" onclick="eliminaImp('@item.Codice')">Elim.</button>
                </td>
            </tr>
        }

    </tbody>
</table>

ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Lista impiegati</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Impiegato/Inserisci">Inserisci impiegato</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/script.js"></script>
</body>
</html>

ASPCORE_Lez4_Impiegati/ASPCORE_Lez4_Impiegati/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <!-- BOOTSTRAP -->
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>